### ISSUE TITLE
Gulp build fails - Error in plugin "gulp-less"

### ISSUE THREAD

**Issue by j055** [fomantic/Fomantic-UI#1429]
# Bug Report
Gulp build fails at 'Building compressed CSS'

## Steps to reproduce
gulp build

## Expected result
Complete without errors

## Actual result

```
D:\source\repos\app\semantic>gulp build
[13:54:26] Using gulpfile D:\source\repos\app\semantic\gulpfile.js
[13:54:26] Starting 'build'...
Building Semantic
[13:54:26] Starting 'build-css'...
[13:54:26] Starting 'Building uncompressed CSS'...
[13:54:26] Starting 'Building compressed CSS'...
Potentially unhandled rejection [2] Error: Error in plugin "gulp-less"
Message:
    Unrecognised input in file D:\source\repos\app\semantic\src\themes\default\globals\colors.less line no. 492
Details:
    type: Parse
    filename: D:\source\repos\app\semantic\src\themes\default\globals\colors.less
    index: 18389
    line: 492
    callLine: NaN
    callExtract: undefined
    column: 0
    extract: ,@formStates: {,  @error: {
    lineNumber: 492
    fileName: D:\source\repos\app\semantic\src\themes\default\globals\colors.less

    at DestroyableTransform.errorHandler (D:\source\repos\app\semantic\tasks\config\tasks.js:124:19)
    at DestroyableTransform.emit (events.js:187:15)
    at DestroyableTransform.EventEmitter.emit (domain.js:441:20)
    at onwriteError (D:\source\repos\app\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:449:12)
    at onwrite (D:\source\repos\app\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:470:11)
    at WritableState.onwrite (D:\source\repos\app\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:180:5)
    at DestroyableTransform.afterTransform (D:\source\repos\app\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:93:3)
    at D:\source\repos\app\node_modules\gulp-less\index.js:58:14
    at tryCatchReject (D:\source\repos\app\node_modules\when\lib\makePromise.js:845:30)
    at runContinuation1 (D:\source\repos\app\node_modules\when\lib\makePromise.js:804:4)
Potentially unhandled rejection [4] Error: Error in plugin "gulp-less"
Message:
    Unrecognised input in file D:\source\repos\app\semantic\src\themes\default\globals\colors.less line no. 492
Details:
    type: Parse
    filename: D:\source\repos\app\semantic\src\themes\default\globals\colors.less
    index: 18389
    line: 492
    callLine: NaN
    callExtract: undefined
    column: 0
    extract: ,@formStates: {,  @error: {
    lineNumber: 492
    fileName: D:\source\repos\app\semantic\src\themes\default\globals\colors.less

    at DestroyableTransform.errorHandler (D:\source\repos\app\semantic\tasks\config\tasks.js:124:19)
    at DestroyableTransform.emit (events.js:187:15)
    at DestroyableTransform.EventEmitter.emit (domain.js:441:20)
    at onwriteError (D:\source\repos\app\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:449:12)
    at onwrite (D:\source\repos\app\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:470:11)
    at WritableState.onwrite (D:\source\repos\app\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:180:5)
    at DestroyableTransform.afterTransform (D:\source\repos\app\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:93:3)
    at D:\source\repos\app\node_modules\gulp-less\index.js:58:14
    at tryCatchReject (D:\source\repos\app\node_modules\when\lib\makePromise.js:845:30)
    at runContinuation1 (D:\source\repos\app\node_modules\when\lib\makePromise.js:804:4)
[13:54:26] The following tasks did not complete: build, build-css, <series>, <series>, Building uncompressed CSS, Building compressed CSS
[13:54:26] Did you forget to signal async completion?
```

## Version
2.8.4

**Comment by lubber-de** [comment]
Does `npx gulp build` work?

**Comment by lubber-de** [comment]
You seem to have changed either the colors.less file or you have installed an old vesion of LESS

**Comment by j055** [comment]
```npx gulp build``` gives the same result

**Comment by j055** [comment]
It's a new file because I've upgraded from ```semantic-ui v2.4.2```

**Comment by j055** [comment]
```package.json``` extract:

```
"gulp": "^4.0.0",
    "gulp-autoprefixer": "^6.0.0",
    "gulp-chmod": "^2.0.0",
    "gulp-clean-css": "^3.10.0",
    "gulp-clone": "^2.0.1",
    "gulp-concat": "^2.6.1",
    "gulp-concat-css": "^3.1.0",
    "gulp-copy": "^4.0.0",
    "gulp-dedupe": "0.0.2",
    "gulp-flatten": "^0.4.0",
    "gulp-header": "^2.0.5",
    "gulp-if": "^2.0.2",
    "gulp-json-editor": "^2.4.3",
    "gulp-less": "^4.0.1",
    "gulp-notify": "^3.0.0",
    "gulp-plumber": "^1.1.0",
    "gulp-print": "^5.0.0",
    "gulp-rename": "^1.4.0",
    "gulp-replace": "^1.0.0",
    "gulp-rtlcss": "^1.3.0",
    "gulp-uglify": "^3.0.1",
```

**Comment by lubber-de** [comment]
What version is shown for the less package?
`npm show less version`

**Comment by j055** [comment]
```3.11.1```

**Comment by lubber-de** [comment]
Did you uninstall the semantic-ui 2.4.2 package before installing fomantic-ui?

**Comment by j055** [comment]
Possibly not the first time :).

**Comment by j055** [comment]
Looks like ```less``` package was an older version even though the ```npm``` showed the latest. I have uninstalled and installed again, and run the build and all looks good.

Thanks for your all you help.
