### ISSUE TITLE
[bug] Error when building Fomantic UI using gulp

### ISSUE THREAD

**Issue by batata004** [fomantic/Fomantic-UI#2530]
Hello,

I already used gulp in the past to build Fomantic UI and it worked perfetcly all the times. But this time I am facing an error when using the 2.9.0 version (I followed exactly the instructions at Getting Started to build the project with the updated instructions that are a little bit different on the 2.9.0 version). When I execute the command below:

`npx gulp build`

It shows:
```

[19:28:33] Using gulpfile C:\fomantic-ui\semantic\gulpfile.js
[19:28:33] Starting 'build'...
Building Semantic
[19:28:33] Starting 'build-css'...
[19:28:33] Starting 'Building uncompressed CSS'...
[19:28:33] Starting 'Building compressed CSS'...
[19:28:33] Created: dist\components\reset.min.css
[19:28:33] Created: dist\components\reset.css
[19:28:33] Created: dist\components\site.css
[19:28:33] Created: dist\components\site.min.css
[19:28:34] Created: dist\components\button.css
[19:28:34] Created: dist\components\button.min.css
[19:28:34] 'Building uncompressed CSS' errored after 805 ms
[19:28:34] Error: Error in plugin "gulp-less"
Message:
    Error evaluating function `each`: variable @formStates is undefined in file C:\fomantic-ui\semantic\src\definitions\collections\form.less line no. 502
Details:
    type: Name
    filename: C:\fomantic-ui\semantic\src\definitions\collections\form.less
    index: 12053
    line: 502
    column: 2
    callLine: NaN
    callExtract: undefined
    extract:   ---------------------*/,  each(@variationFormStates, {,    @state: @value;
    lineNumber: 502
    fileName: C:\fomantic-ui\semantic\src\definitions\collections\form.less

    at Transform.errorHandler (C:\fomantic-ui\semantic\tasks\config\tasks.js:125:19)
    at Transform.emit (node:events:525:35)
    at Transform.emit (node:domain:489:12)
    at errorOrDestroy (C:\fomantic-ui\node_modules\gulp-less\node_modules\readable-stream\lib\internal\streams\destroy.js:98:101)
    at onwriteError (C:\fomantic-ui\node_modules\gulp-less\node_modules\readable-stream\lib\_stream_writable.js:430:5)
    at onwrite (C:\fomantic-ui\node_modules\gulp-less\node_modules\readable-stream\lib\_stream_writable.js:450:11)
    at WritableState.onwrite (C:\fomantic-ui\node_modules\gulp-less\node_modules\readable-stream\lib\_stream_writable.js:160:5)
    at Transform.afterTransform (C:\fomantic-ui\node_modules\gulp-less\node_modules\readable-stream\lib\_stream_transform.js:89:3)
    at C:\fomantic-ui\node_modules\gulp-less\index.js:109:14
[19:28:34] 'build-css' errored after 808 ms
[19:28:34] 'build' errored after 811 ms
```

On the file "variation.variables" I have this:

```
/* Form */
...
@variationFormStates: error;
...
```

Even if I try to use the line below, the error still happens:

```
@variationFormStates: @variationAllStates;
```

If you need any more information, file... I am here to provide you with everything you need!

The only files that I made any change (from the default), are below:

My `color.less` file has this:
```

/***********************************************************
  Central Color Mapping Base for all components to iterate
***********************************************************/

@colors: {
  @primary: {
    color          : @primaryColor;
    light          : @lightPrimaryColor;
    border         : @primaryBorderColor;
    background     : @primaryBackground;
    header         : @primaryHeaderColor;
    boxShadow      : @primaryBoxShadow;
    boxFloatShadow : @primaryBoxFloatingShadow;
    text           : @primaryTextColor;
    lightText      : @lightPrimaryTextColor;
    hoverText      : @primaryHoverTextColor;
    focus          : @primaryColorFocus;
    lightFocus     : @lightPrimaryColorFocus;
    down           : @primaryColorDown;
    lightDown      : @lightPrimaryColorDown;
    active         : @primaryColorActive;
    lightActive    : @lightPrimaryColorActive;
    shadow         : @primaryTextShadow;
    lightShadow    : @lightPrimaryTextShadow;
    hover          : @primaryColorHover;
    lightHover     : @lightPrimaryColorHover;
    ribbon         : @primaryRibbonShadow;
    invertedRibbon : @primaryInvertedRibbonShadow;
    tertiary       : @primaryTertiaryColor;
    tertiaryHover  : @primaryTertiaryColorHover;
    tertiaryFocus  : @primaryTertiaryColorFocus;
    tertiaryActive : @primaryTertiaryColorActive;
    bright         : @primaryBright;
    brightHover    : @primaryBrightHover;
    isDark         : false;
    isVeryDark     : false;
  };
  @red: {
    color          : @red;
    light          : @lightRed;
    border         : @redBorderColor;
    background     : @redBackground;
    header         : @redHeaderColor;
    boxShadow      : @redBoxShadow;
    boxFloatShadow : @redBoxFloatingShadow;
    text           : @redTextColor;
    lightText      : @lightRedTextColor;
    hoverText      : @redHoverTextColor;
    focus          : @redFocus;
    lightFocus     : @lightRedFocus;
    down           : @redDown;
    lightDown      : @lightRedDown;
    active         : @redActive;
    lightActive    : @lightRedActive;
    shadow         : @redTextShadow;
    lightShadow    : @lightRedTextShadow;
    hover          : @redHover;
    lightHover     : @lightRedHover;
    ribbon         : @redRibbonShadow;
    invertedRibbon : @redInvertedRibbonShadow;
    tertiary       : @redTertiaryColor;
    tertiaryHover  : @redTertiaryColorHover;
    tertiaryFocus  : @redTertiaryColorFocus;
    tertiaryActive : @redTertiaryColorActive;
    bright         : @redBright;
    brightHover    : @redBrightHover;
    isDark         : false;
    isVeryDark     : false;
  };
}
```

My `site.variables` file has this:
```

/*******************************
     User Global Variables
*******************************/

@importGoogleFonts : false;
@fontName          : inherit;
@headerFont        : @fontName;
@pageFont          : @fontName;
@googleFontName    : @fontName;
```

My `variation.variables` file has this:

```
/***********************************************************
  Central element variation compilation enablers
***********************************************************/

/* General */
@variationAllSizes: mini, tiny, small, large, big, huge, massive;
@variationAllColors: primary, secondary, red, orange, yellow, olive, green, teal, blue, violet, purple, pink, brown, grey, black;
@variationAllStates: error, info, success, warning;
@variationAllConsequences: positive, negative, error, info, success, warning;

/*******************************
           Elements
*******************************/

/* Button */
@variationButtonDisabled: false;
@variationButtonAnimated: false;
@variationButtonAnimatedFade: false;
@variationButtonInverted: false;
@variationButtonSocial: true;
@variationButtonFloated: false;
@variationButtonCompact: false;
@variationButtonIcon: false;
@variationButtonLoading: false;
@variationButtonBasic: false;
@variationButtonTertiary: false;
@variationButtonLabeled: false;
@variationButtonLabeledIcon: true;
@variationButtonToggle: false;
@variationButtonOr: false;
@variationButtonAttached: false;
@variationButtonFluid: false;
@variationButtonEqualWidth: false;
@variationButtonVertical: false;
@variationButtonCircular: false;
@variationButtonGroups: false;
@variationButtonStackable: false;
@variationButtonWrapping: false;
@variationButtonWrapped: false;
@variationButtonSpaced: false;
@variationButtonSizes: mini, tiny, small, big;
@variationButtonColors: red;

/* Container */
@variationContainerGrid: true;
@variationContainerRelaxed: true;
@variationContainerVeryRelaxed: true;
@variationContainerText: true;
@variationContainerWide: true;
@variationContainerFluid: true;
@variationContainerAligned: true;
@variationContainerJustified: true;
@variationContainerScrolling: true;
@variationContainerScrollingShort: true;
@variationContainerScrollingVeryShort: true;
@variationContainerScrollingLong: true;
@variationContainerScrollingVeryLong: true;

/* Divider */
@variationDividerInverted: true;
@variationDividerHorizontal: true;
@variationDividerVertical: true;
@variationDividerIcon: true;
@variationDividerHidden: true;
@variationDividerFitted: true;
@variationDividerClearing: true;
@variationDividerSection: true;
@variationDividerSizes: @variationAllSizes;
@variationDividerColors: @variationAllColors;

/* Header */
@variationHeaderDisabled: true;
@variationHeaderInverted: true;
@variationHeaderSub: true;
@variationHeaderIcon: true;
@variationHeaderAligned: true;
@variationHeaderJustified: true;
@variationHeaderFloated: true;
@variationHeaderFitted: true;
@variationHeaderDividing: true;
@variationHeaderBlock: true;
@variationHeaderAttached: true;
@variationHeaderTags: h1, h2, h3, h4, h5, h6;
@variationHeaderSizes: @variationAllSizes;
@variationHeaderColors: @variationAllColors;

/* Icon */
@variationIconDeprecated: true;
@variationIconSolid: true;
@variationIconAliases: true;
@variationIconOutline: true;
@variationIconBrand: true;
@variationIconThin: true; /* Font Awesome Pro only */
@variationIconDisabled: true;
@variationIconInverted: true;
@variationIconLoading: true;
@variationIconFitted: true;
@variationIconLink: true;
@variationIconCircular: true;
@variationIconBordered: true;
@variationIconColored: true;
@variationIconRotated: true;
@variationIconFlipped: true;
@variationIconCorner: true;
@variationIconGroups: true;
@variationIconSizes: @variationAllSizes;
@variationIconColors: @variationAllColors;

/* Image */
@variationImageDisabled: true;
@variationImageCircular: true;
@variationImageBordered: true;
@variationImageRounded: true;
@variationImageInline: true;
@variationImageAligned: true;
@variationImageFluid: true;
@variationImageAvatar: true;
@variationImageFloated: true;
@variationImageSpaced: true;
@variationImageCentered: true;
@variationImageGroups: true;
@variationImageSizes: @variationAllSizes;

/* Input */
@variationInputDisabled: false;
@variationInputInverted: false;
@variationInputStates: @variationAllStates;
@variationInputTransparent: false;
@variationInputCorner: false;
@variationInputLoading: false;
@variationInputIcon: false;
@variationInputLabeled: false;
@variationInputAction: false;
@variationInputFluid: false;
@variationInputFile: false;
@variationInputColors: false;
@variationInputSizes: @variationAllSizes;

/* Label */
@variationLabelDisabled: false;
@variationLabelInverted: false;
@variationLabelImage: false;
@variationLabelTag: true;
@variationLabelCorner: false;
@variationLabelRibbon: false;
@variationLabelCircular: false;
@variationLabelPointing: false;
@variationLabelFloating: false;
@variationLabelBasic: true;
@variationLabelAttached: false;
@variationLabelFluid: true;
@variationLabelSizes: @variationAllSizes;
@variationLabelColors: false;

/* List */
@variationListInverted: true;
@variationListDisabled: true;
@variationListBulleted: true;
@variationListOrdered: true;
@variationListIcon: true;
@variationListImage: true;
@variationListFloated: true;
@variationListLink: true;
@variationListAligned: true;
@variationListFitted: true;
@variationListAnimated: true;
@variationListHorizontal: true;
@variationListSuffixed: true;
@variationListSelection: true;
@variationListDivided: true;
@variationListCelled: true;
@variationListRelaxed: true;
@variationListVeryRelaxed: true;
@variationListHeader: true;
@variationListDescription: true;
@variationListSizes: @variationAllSizes;

/* Loader */
@variationLoaderSpeeds: true;
@variationLoaderIndeterminate: true;
@variationLoaderText: true;
@variationLoaderInline: true;
@variationLoaderElastic: true;
@variationLoaderSizes: @variationAllSizes;
@variationLoaderColors: @variationAllColors;

/* Placeholder */
@variationPlaceholderInverted: true;
@variationPlaceholderImage: true;
@variationPlaceholderLine: true;
@variationPlaceholderHeader: true;
@variationPlaceholderFluid: true;
@variationPlaceholderLengths: true;

/* Rail */
@variationRailInternal: true;
@variationRailDividing: true;
@variationRailDistance: true;
@variationRailAttached: true;
@variationRailSizes: @variationAllSizes;

/* Reveal */
@variationRevealDisabled: true;
@variationRevealSlide: true;
@variationRevealFade: true;
@variationRevealMove: true;
@variationRevealRotate: true;
@variationRevealSizes: @variationAllSizes;

/* Segment */
@variationSegmentInverted: true;
@variationSegmentDisabled: true;
@variationSegmentVertical: true;
@variationSegmentPlaceholder: true;
@variationSegmentHorizontal: true;
@variationSegmentPiled: true;
@variationSegmentStacked: true;
@variationSegmentPadded: true;
@variationSegmentVeryPadded: true;
@variationSegmentCircular: true;
@variationSegmentCompact: true;
@variationSegmentRaised: true;
@variationSegmentGroups: true;
@variationSegmentBasic: true;
@variationSegmentClearing: true;
@variationSegmentLoading: true;
@variationSegmentFloating: true;
@variationSegmentAligned: true;
@variationSegmentSecondary: true;
@variationSegmentTertiary: true;
@variationSegmentAttached: true;
@variationSegmentFitted: true;
@variationSegmentScrolling: true;
@variationSegmentScrollingShort: true;
@variationSegmentScrollingVeryShort: true;
@variationSegmentScrollingLong: true;
@variationSegmentScrollingVeryLong: true;
@variationSegmentSizes: @variationAllSizes;
@variationSegmentColors: @variationAllColors;

/* Step */
@variationStepInverted: true;
@variationStepDisabled: true;
@variationStepStackable: true;
@variationStepVertical: true;
@variationStepOrdered: true;
@variationStepFluid: true;
@variationStepAttached: true;
@variationStepEqualWidth: true;
@variationStepSizes: @variationAllSizes;

/* Text */
@variationTextInverted: true;
@variationTextDisabled: true;
@variationTextStates: @variationAllStates;
@variationTextSizes: @variationAllSizes;
@variationTextColors: @variationAllColors;


/*******************************
           Collections
*******************************/

/* Breadcrumb */
@variationBreadcrumbInverted: true;
@variationBreadcrumbSizes: @variationAllSizes;

/* Form */
@variationFormInverted: false;
@variationFormDisabled: false;
@variationFormTransparent: false;
@variationFormLoading: false;
@variationFormStates: error;
@variationFormRequired: false;
@variationFormInline: false;
@variationFormGrouped: false;
@variationFormEqualWidth: false;
@variationFormWide: false;
@variationFormSizes: false;

/* Grid */
@variationGridInverted: true;
@variationGridPage: true;
@variationGridCelled: true;
@variationGridCentered: true;
@variationGridRelaxed: true;
@variationGridVeryRelaxed: true;
@variationGridPadded: true;
@variationGridFloated: true;
@variationGridDivided: true;
@variationGridVertical: true;
@variationGridAligned: true;
@variationGridStretched: true;
@variationGridJustified: true;
@variationGridReversed: true;
@variationGridDoubling: true;
@variationGridStackable: true;
@variationGridCompact: true;
@variationGridVeryCompact: true;
@variationGridWide: true;
@variationGridEqualWidth: true;
@variationGridColors: @variationAllColors;

/* Menu */
@variationMenuInverted: false;
@variationMenuSecondary: false;
@variationMenuPointing: false;
@variationMenuVertical: false;
@variationMenuTabular: false;
@variationMenuPagination: false;
@variationMenuText: false;
@variationMenuFluid: false;
@variationMenuLabeled: false;
@variationMenuStackable: false;
@variationMenuFloated: false;
@variationMenuCentered: false;
@variationMenuFitted: false;
@variationMenuBorderless: false;
@variationMenuCompact: false;
@variationMenuFixed: false;
@variationMenuAttached: false;
@variationMenuIcon: false;
@variationMenuEqualWidth: false;
@variationMenuSizes: false;
@variationMenuColors: false;

/* Message */
@variationMessageInverted: false;
@variationMessageCompact: false;
@variationMessageAttached: false;
@variationMessageIcon: false;
@variationMessageFloating: false;
@variationMessageConsequences: false;
@variationMessageCentered: false;
@variationMessageRightAligned: false;
@variationMessageSizes: false;
@variationMessageColors: false;

/* Table */
@variationTableInverted: true;
@variationTableDisabled: true;
@variationTableDefinition: true;
@variationTableStructured: true;
@variationTablePositive: true;
@variationTableNegative: true;
@variationTableError: true;
@variationTableWarning: true;
@variationTableActive: true;
@variationTableStackable: true;
@variationTableAligned: true;
@variationTableFixed: true;
@variationTableSelectable: true;
@variationTableAttached: true;
@variationTableStriped: true;
@variationTableSortable: true;
@variationTableCollapsing: true;
@variationTableBasic: true;
@variationTableVeryBasic: true;
@variationTableCelled: true;
@variationTablePadded: true;
@variationTableVeryPadded: true;
@variationTableCompact: true;
@variationTableVeryCompact: true;
@variationTableMarked: true;
@variationTableEqualWidth: true;
@variationTableWide: true;
@variationTableScrolling: true;
@variationTableScrollingShort: true;
@variationTableScrollingVeryShort: true;
@variationTableScrollingLong: true;
@variationTableScrollingVeryLong: true;
@variationTableStuck: true;
@variationTableStuckHead: true;
@variationTableStuckFoot: true;
@variationTableStuckFirst: true;
@variationTableStuckLast: true;
@variationTableOverflowing: true;
@variationTableOverflowingShort: true;
@variationTableOverflowingVeryShort: true;
@variationTableOverflowingLong: true;
@variationTableOverflowingVeryLong: true;
@variationTableSizes: @variationAllSizes;
@variationTableColors: @variationAllColors;


/*******************************
             Views
*******************************/

/* Ad */
@variationAdLeaderboard: true;
@variationAdBillboard: true;
@variationAdPanorama: true;
@variationAdNetboard: true;
@variationAdRectangle: true;
@variationAdSquare: true;
@variationAdButton: true;
@variationAdSkyscraper: true;
@variationAdBanner: true;
@variationAdMobile: true;
@variationAdCentered: true;
@variationAdTest: true;

/* Card */
@variationCardInverted: true;
@variationCardBasic: true;
@variationCardDisabled: true;
@variationCardLoading: true;
@variationCardHorizontal: true;
@variationCardRaised: true;
@variationCardCentered: true;
@variationCardFluid: true;
@variationCardLink: true;
@variationCardDoubling: true;
@variationCardStackable: true;
@variationCardFloated: true;
@variationCardAligned: true;
@variationCardImage: true;
@variationCardHeader: true;
@variationCardDescription: true;
@variationCardMeta: true;
@variationCardExtra: true;
@variationCardButton: true;
@variationCardStar: true;
@variationCardLike: true;
@variationCardEqualWidth: true;
@variationCardSizes: @variationAllSizes;
@variationCardColors: @variationAllColors;

/* Comment */
@variationCommentInverted: true;
@variationCommentThreaded: true;
@variationCommentMinimal: true;
@variationCommentAvatar: true;
@variationCommentAuthor: true;
@variationCommentMeta: true;
@variationCommentActions: true;
@variationCommentReply: true;
@variationCommentSizes: @variationAllSizes;
@variationCommentColors: @variationAllColors;

/* Feed */
@variationFeedInverted: true;
@variationFeedMeta: true;
@variationFeedSummary: true;
@variationFeedUser: true;
@variationFeedExtra: true;
@variationFeedDate: true;
@variationFeedLike: true;
@variationFeedSizes: @variationAllSizes;

/* Item */
@variationItemInverted: true;
@variationItemImage: true;
@variationItemHeader: true;
@variationItemDescription: true;
@variationItemMeta: true;
@variationItemExtra: true;
@variationItemFavorite: true;
@variationItemLike: true;
@variationItemFloated: true;
@variationItemAligned: true;
@variationItemRelaxed: true;
@variationItemVeryRelaxed: true;
@variationItemDivided: true;
@variationItemLink: true;
@variationItemUnstackable: true;
@variationItemSizes: @variationAllSizes;

/* Statistic */
@variationStatisticInverted: true;
@variationStatisticStackable: true;
@variationStatisticFloated: true;
@variationStatisticHorizontal: true;
@variationStatisticEqualWidth: true;
@variationStatisticSizes: @variationAllSizes;
@variationStatisticColors: @variationAllColors;


/*******************************
            Modules
*******************************/

/* Accordion */
@variationAccordionInverted: true;
@variationAccordionStyled: true;
@variationAccordionBasicStyled: true;
@variationAccordionFluid: true;
@variationAccordionCompact: true;
@variationAccordionVeryCompact: true;
@variationAccordionRightDropdown: true;
@variationAccordionTree: true;

/* Calendar */
@variationCalendarInverted: true;
@variationCalendarDisabled: true;
@variationCalendarMultiMonth: true;

/* Checkbox */
@variationCheckboxDisabled: false;
@variationCheckboxReadonly: false;
@variationCheckboxInverted: false;
@variationCheckboxRadio: false;
@variationCheckboxSlider: false;
@variationCheckboxToggle: true;
@variationCheckboxIndeterminate: false;
@variationCheckboxFitted: false;
@variationCheckboxRightAligned: false;
@variationCheckboxSizes: false;
@variationCheckboxColors: false;

/* Dimmer */
@variationDimmerInverted: false;
@variationDimmerDisabled: false;
@variationDimmerLegacy: true;
@variationDimmerAligned: false;
@variationDimmerPage: true;
@variationDimmerBlurring: false;
@variationDimmerShades: false;
@variationDimmerSimple: false;
@variationDimmerPartially: false;

/* Dropdown */
@variationDropdownInverted: true;
@variationDropdownDisabled: true;
@variationDropdownReadonly: true;
@variationDropdownLabel: true;
@variationDropdownButton: true;
@variationDropdownSelection: true;
@variationDropdownShort: true;
@variationDropdownLong: true;
@variationDropdownCompact: true;
@variationDropdownSearch: true;
@variationDropdownMultiple: true;
@variationDropdownInline: true;
@variationDropdownLoading: true;
@variationDropdownStates: false;
@variationDropdownClear: true;
@variationDropdownLeft: true;
@variationDropdownUpward: true;
@variationDropdownSimple: true;
@variationDropdownScrolling: true;
@variationDropdownFluid: true;
@variationDropdownFloating: true;
@variationDropdownPointing: true;
@variationDropdownColumnar: true;
@variationDropdownScrollhint: true;
@variationDropdownSizes: false;

/* Embed */
@variationEmbedRatio: true;

/* Flyout */
@variationFlyoutInverted: true;
@variationFlyoutBasic: true;
@variationFlyoutFullscreen: true;
@variationFlyoutCentered: true;
@variationFlyoutActions: true;
@variationFlyoutLeftActions: true;
@variationFlyoutBlurring: true;
@variationFlyoutColumnWidth: true;
@variationFlyoutThin: true;
@variationFlyoutWide: true;
@variationFlyoutTop: true;
@variationFlyoutBottom: true;
@variationFlyoutLeft: true;
@variationFlyoutRight: true;
@variationFlyoutOverlay: true;

/* Modal */
@variationModalInverted: false;
@variationModalBasic: true;
@variationModalFullscreen: false;
@variationModalOverlay: false;
@variationModalAligned: false;
@variationModalScrolling: false;
@variationModalLegacy: false;
@variationModalCloseInside: true;
@variationModalCentered: false;
@variationModalActions: false;
@variationModalLeftActions: false;
@variationModalSizes: small;

/* Nag */
@variationNagInverted: true;
@variationNagBottom: true;
@variationNagOverlay: true;
@variationNagFixed: true;
@variationNagGroups: true;
@variationNagSizes: @variationAllSizes;
@variationNagColors: @variationAllColors;

/* Popup */
@variationPopupInverted: true;
@variationPopupTooltip: true;
@variationPopupPosition: true;
@variationPopupTop: true;
@variationPopupBottom: true;
@variationPopupLeft: true;
@variationPopupRight: true;
@variationPopupCenter: true;
@variationPopupLoading: true;
@variationPopupBasic: true;
@variationPopupWide: true;
@variationPopupFluid: false;
@variationPopupFlowing: false;
@variationPopupFixed: false;
@variationPopupSizes: false;
@variationPopupColors: false;

/* Progress */
@variationProgressInverted: true;
@variationProgressDisabled: true;
@variationProgressIndicating: true;
@variationProgressIndeterminate: true;
@variationProgressSliding: true;
@variationProgressFilling: true;
@variationProgressSwinging: true;
@variationProgressMultiple: true;
@variationProgressSuccess: true;
@variationProgressWarning: true;
@variationProgressError: true;
@variationProgressActive: true;
@variationProgressAttached: true;
@variationProgressSpeeds: true;
@variationProgressRightAligned: true;
@variationProgressSizes: @variationAllSizes;
@variationProgressColors: @variationAllColors;

/* Rating */
@variationRatingDisabled: true;
@variationRatingPartial: true;
@variationRatingSizes: @variationAllSizes;
@variationRatingColors: @variationAllColors;

/* Search */
@variationSearchDisabled: true;
@variationSearchSelection: true;
@variationSearchCategory: true;
@variationSearchLoading: true;
@variationSearchAligned: true;
@variationSearchFluid: true;
@variationSearchShort: true;
@variationSearchVeryShort: true;
@variationSearchLong: true;
@variationSearchVeryLong: true;
@variationSearchScrolling: true;
@variationSearchSizes: @variationAllSizes;

/* Shape */
@variationShapeCube: true;
@variationShapeText: true;
@variationShapeLoading: true;

/* Sidebar */
@variationSidebarThin: true;
@variationSidebarVeryThin: true;
@variationSidebarWide: true;
@variationSidebarVeryWide: true;
@variationSidebarTop: true;
@variationSidebarBottom: true;
@variationSidebarLeft: true;
@variationSidebarRight: true;
@variationSidebarOverlay: true;
@variationSidebarSlideAlong: true;
@variationSidebarSlideOut: true;
@variationSidebarScale: true;
@variationSidebarPush: true;
@variationSidebarUncover: true;
@variationSidebarBlurring: true;

/* Slider */
@variationSliderInverted: true;
@variationSliderDisabled: true;
@variationSliderReversed: true;
@variationSliderLabeled: true;
@variationSliderTicked: true;
@variationSliderVertical: true;
@variationSliderBasic: true;
@variationSliderSizes: small, large, big;
@variationSliderColors: @variationAllColors;

/* Tab */
@variationTabLoading: true;

/* Toast */
@variationToastInverted: true;
@variationToastTop: true;
@variationToastBottom: true;
@variationToastLeft: true;
@variationToastRight: true;
@variationToastCenter: true;
@variationToastCentered: true;
@variationToastInfo: true;
@variationToastWarning: true;
@variationToastSuccess: true;
@variationToastError: true;
@variationToastHorizontal: true;
@variationToastFloating: true;
@variationToastProgress: true;
@variationToastIcon: true;
@variationToastClose: true;
@variationToastImage: true;
@variationToastMessage: true;
@variationToastCard: true;
@variationToastActions: true;
@variationToastVertical: true;
@variationToastAttached: true;
@variationToastCompact: true;
@variationToastCentered: true;
@variationToastColors: @variationAllColors;

/* Transition */
@variationTransitionDisabled: false;
@variationTransitionLoading: false;
@variationTransitionBrowse: false;
@variationTransitionDrop: false;
@variationTransitionFade: true;
@variationTransitionFlip: true;
@variationTransitionScale: true;
@variationTransitionFly: true;
@variationTransitionSlide: false;
@variationTransitionSwing: false;
@variationTransitionZoom: false;
@variationTransitionFlash: false;
@variationTransitionShake: false;
@variationTransitionBounce: false;
@variationTransitionTada: false;
@variationTransitionPulse: false;
@variationTransitionJiggle: false;
@variationTransitionGlow: false;

/* Emojis */
@variationEmojiColons: true;
@variationEmojiNoColons: true;
@variationEmojiDisabled: true;
@variationEmojiLoading: true;
@variationEmojiLink: true;

```

**Comment by lubber-de** [comment]
It seems you have deleted the `@formStates` colors definitions map from `colors.less`
https://github.com/fomantic/Fomantic-UI/blob/51e0c4513f9514c665f32af7ee0fbf80c3fe08a9/src/themes/default/globals/colors.less#L492-L494

**Comment by batata004** [comment]
@lubber-de  IT WORKED PERFECTLY!!!! THANK YOU! Your answer made me think: I dont need to remove colors from `colors.less`, I just need to prevent using then at the `variation.variables` file. It looks to work, I checked the files at the `/dist/` and the colors that I didnt use, didnt show up in the file! Except one thing: `positive` and `negative` class show up in many different places at the `/dist/` files. How do I prevent those `positive` and `negative`  classes from appearing in the `/dist/` files? If they were simply like colors, I could remove then in the `variation.variables` file like I did with all the colors.

**Comment by lubber-de** [comment]
To completely disable a list use `false` instead of an empty string.


However, the button component still always rendered positive/negative buttons (button does not offer more than those two)
I created #2532 to allow this as well.
So all together you can then do

```LESS
@variationAllConsequences: false;
@variationButtonConsequences: false;
```

**Comment by batata004** [comment]
Thank you so much!!! Worked wonderfully!
