### ISSUE TITLE
Unable to install fomantic-ui on clean brew (or semantic-ui)

### ISSUE THREAD

**Issue by romaninsh** [fomantic/Fomantic-UI#306]
# Bug Report

I had to fully uninstall brew and reinstall. After that using Node 11 I'm getting this error after `npm install fomantic-ui`:

```
? Set-up Semantic UI Automatic (Use default locations and all components)
? We detected you are using NPM Nice! Is this your project folder? /Users/rw/tmp (Use arrow keys)
  Yes 
  No, let me specify 
readline.js:1086
            throw err;
            ^

TypeError: Cannot read property 'value' of undefined
    at Prompt.getCurrentValue (/Users/rw/tmp/node_modules/inquirer/lib/prompts/list.js:126:51)
    at tryCatcher (/Users/rw/tmp/node_modules/rx-lite/rx.lite.js:67:31)
    at InnerObserver.next (/Users/rw/tmp/node_modules/rx-lite/rx.lite.js:4495:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/rw/tmp/node_modules/rx-lite/rx.lite.js:1602:31)
    at InnerObserver.tryCatcher (/Users/rw/tmp/node_modules/rx-lite/rx.lite.js:67:31)
    at AutoDetachObserverPrototype.next (/Users/rw/tmp/node_modules/rx-lite/rx.lite.js:6495:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/rw/tmp/node_modules/rx-lite/rx.lite.js:1602:31)
    at TakeObserver.next (/Users/rw/tmp/node_modules/rx-lite/rx.lite.js:4681:17)
    at TakeObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/rw/tmp/node_modules/rx-lite/rx.lite.js:1602:31)
    at TakeObserver.tryCatcher (/Users/rw/tmp/node_modules/rx-lite/rx.lite.js:67:31)
npm WARN enoent ENOENT: no such file or directory, open '/Users/rw/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fomantic-ui@2.6.4 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fomantic-ui@2.6.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rw/.npm/_logs/2018-12-17T13_25_24_434Z-debug.log
```

Related to https://github.com/Semantic-Org/Semantic-UI/issues/6357 ?

## Steps to reproduce
1. uninstall brew
2. remove /usr/local/.. (be careful not to loose anything important! i left "etc" and "var")
3. install npm, etc
4. `npm install fomantic-ui`

**Comment by prudho** [comment]
I had issues trying to build FUI using Node 11, then I step back and everything is running fine. Try to downgrade to Node 10.

**Comment by ColinFrick** [comment]
Not selecting an option for the project folder question (Yes/No) throws this error.

**Comment by romaninsh** [comment]
Tried with `node@10` and having same error.

Tried steps in 6357, but using "Fomantic" repository, got this error at the last step:

```
Romanss-Mac-mini:Fomantic-UI rw$ npm install

> fomantic-ui@2.6.4 install /Users/rw/tmp/tmp2/Fomantic-UI
> gulp install

internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/Users/rw/tmp/tmp2/Fomantic-UI/node_modules/natives/index.js:140:5)
    at require (/Users/rw/tmp/tmp2/Fomantic-UI/node_modules/natives/index.js:113:12)
    at util.js:25:21
    at req_ (/Users/rw/tmp/tmp2/Fomantic-UI/node_modules/natives/index.js:140:5)
    at require (/Users/rw/tmp/tmp2/Fomantic-UI/node_modules/natives/index.js:113:12)
    at fs.js:42:21
    at req_ (/Users/rw/tmp/tmp2/Fomantic-UI/node_modules/natives/index.js:140:5)
    at Object.req [as require] (/Users/rw/tmp/tmp2/Fomantic-UI/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/rw/tmp/tmp2/Fomantic-UI/node_modules/graceful-fs/fs.js:1:99)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fomantic-ui@2.6.4 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fomantic-ui@2.6.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rw/.npm/_logs/2018-12-17T13_43_22_701Z-debug.log
```

**Comment by romaninsh** [comment]
@ColinFrick Yes, I was hitting "enter" instead of selecting Yes/No option. Regarding my original issue - I'll open another ticket.
