### ISSUE TITLE
ReferenceError: internalBinding is not defined

### ISSUE THREAD

**Issue by romaninsh** [fomantic/Fomantic-UI#307]
# Bug Report

Trying to use Fomantic-UI in my npm project produces error `ReferenceError: internalBinding is not defined`.

``` json
{
  "name": "semantic-saasty",
  "version": "1.0.0",
  "description": "custom semantic-ui for saasty",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "fomantic-ui": "^2.6.4"
  },
  "author": "**",
  "license": "**"
}
```

```
npm install
```

We have tracked the error to the vanilla installation of Fomantic-UI:

## Steps to reproduce
1. clone Fomantic-UI
2. cd Fomantic-UI
3. npm install

## Expected result

Interactive installer should be visible.

## Actual result

```
$ npm install

> fomantic-ui@2.6.4 install /Users/rw/Sites/saasty.io/frontend/css/node_modules/fomantic-ui
> gulp install

internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/Users/rw/Sites/saasty.io/frontend/css/node_modules/natives/index.js:137:5)
    at require (/Users/rw/Sites/saasty.io/frontend/css/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/Users/rw/Sites/saasty.io/frontend/css/node_modules/natives/index.js:137:5)
    at require (/Users/rw/Sites/saasty.io/frontend/css/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/Users/rw/Sites/saasty.io/frontend/css/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/Users/rw/Sites/saasty.io/frontend/css/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/rw/Sites/saasty.io/frontend/css/node_modules/graceful-fs/fs.js:1:99)
npm WARN semantic-saasty@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fomantic-ui@2.6.4 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fomantic-ui@2.6.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rw/.npm/_logs/2018-12-17T13_49_06_942Z-debug.log
make: *** [install] Error 1

```

## Testcase

```
Tried with node@10 and having same error.

Tried steps in 6357, but using "Fomantic" repository, got this error at the last step:

omanss-Mac-mini:Fomantic-UI rw$ npm install inquirer
npm WARN gulp-debug@4.0.0 requires a peer of gulp@>=4 but none is installed. You must install peer dependencies yourself.
npm WARN The package merge-stream is included as both a dev and production dependency.

+ inquirer@6.2.1
updated 1 package and audited 5133 packages in 5.329s
found 14 vulnerabilities (2 low, 4 moderate, 8 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Romanss-Mac-mini:Fomantic-UI rw$ npm install

> fomantic-ui@2.6.4 install /Users/rw/tmp/tmp2/Fomantic-UI
> gulp install

internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/Users/rw/tmp/tmp2/Fomantic-UI/node_modules/natives/index.js:140:5)
    at require (/Users/rw/tmp/tmp2/Fomantic-UI/node_modules/natives/index.js:113:12)
    at util.js:25:21
    at req_ (/Users/rw/tmp/tmp2/Fomantic-UI/node_modules/natives/index.js:140:5)
    at require (/Users/rw/tmp/tmp2/Fomantic-UI/node_modules/natives/index.js:113:12)
    at fs.js:42:21
    at req_ (/Users/rw/tmp/tmp2/Fomantic-UI/node_modules/natives/index.js:140:5)
    at Object.req [as require] (/Users/rw/tmp/tmp2/Fomantic-UI/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/rw/tmp/tmp2/Fomantic-UI/node_modules/graceful-fs/fs.js:1:99)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fomantic-ui@2.6.4 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fomantic-ui@2.6.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rw/.npm/_logs/2018-12-17T13_45_32_773Z-debug.log
Romanss-Mac-mini:Fomantic-UI rw$ node --version
v10.14.2
```

## Screenshot (when possible)
![]()

## Version
 - node 11
 - node 10 (cleaned out node 11)

**Comment by romaninsh** [comment]
Here is something i found:

1. clone Fomantic-UI
2. run `npm install` .. will fail
3. run `gulp build`  .. will fail
4. run `gulp install`  is ok
5. run `gulp build`  .. is ok
6. run `npm install` .. is ok

**Comment by romaninsh** [comment]
another clue is:

Romanss-Mac-mini:Fomantic-UI rw$ npm install gulp
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN gulp-debug@4.0.0 requires a peer of gulp@>=4 but none is installed. You must install peer dependencies yourself.
npm WARN The package merge-stream is included as both a dev and production dependency.

+ gulp@3.9.1
```

Romanss-Mac-mini:css rw$ npm install gulp
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN semantic-saasty@1.0.0 No repository field.

+ gulp@4.0.0
added 158 packages from 91 contributors, removed 449 packages, updated 31 packages, moved 7 packages and audited 5482 packages in 14.835s
found 0 vulnerabilities
```

**Comment by romaninsh** [comment]
Clue lead to workaround:

``` json
  "dependencies": {
    "fomantic-ui": "^2.6.4",
    "gulp": "^3.9.1"
  },
```

With this - our build works again.

**Comment by hammy2899** [comment]
In the next release this issue seems to be fixed but the gulp task seems to hang after selecting the, I will look into this further when I get some time.

@ColinFrick you may also want to have a look.
